const express = require('express');
const cors = require('cors');
const teacherRouter = require('./routers/teacherRouter');
const { invalidUrl } = require('./utils/customFunctions.js');
const app = express();
app.use(cors());
app.use(express.urlencoded({ extended: false }));
app.use(express.json());
app.use('/online-test/teacher', teacherRouter);
app.all('*', invalidUrl);
module.exports = app;
